### Get posts
GET https://jsonplaceholder.typicode.com/posts/1

### Post posts
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
X-Api-Key: asd

{
  "title": "hello from athas",
  "body": "testing the http client"
}
